### ISSUE TITLE
How do you generate pdfs for grid?

### ISSUE THREAD

**Issue by kalwar** [haiwan/Exporter#11]
Hi,

Thank you for your great addon. I like this very much. Is there any way you can also generate pdfs for vaadin grid?

**Comment by M0rfic** [comment]
The PdfExporter constructor accept tables or containers. Thus you can do something like `        PdfExporter exporter = new PdfExporter(myGrid.getContainerDataSource(), my.getContainerDataSource().getContainerPropertyIds().toArray());`. The property IDs are necessary because you'll get a NPE otherwise, probably due to a bug but I did not have the time to investigate myself.

**Comment by kalwar** [comment]
Thanks... it works.  :+1:
